-- AlterTable
ALTER TABLE "User" ADD COLUMN "xp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "freeCaseOpens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "enterLevelRewardedUpTo" INTEGER NOT NULL DEFAULT 1;
